### PR TITLE
Include Manar Solutions  

### PR DESCRIPTION
**Pull request by ManarOmar**
⚠️ THIS IS A PULL REQUEST TEMPLATE! ⚠️ This helps you complete a pull request. Please follow the instructions below. 

## Submission Checklist ✅

-   [x] I have revised my code at least twice.
-   [x] I have followed PEP8 guidelines.
-   [x] I added the tests I ran to ensure the correctness of my code
-   [x] I have added the unnecessary files (venvs files, etc.) to the `.gitignore`.

-   [x] I have applied the `waiting for review` label to my pull request.

### CODE REVIEW

**Comment by ndrwnaguib** [comment]
Hello @ManarOmar! Welcome to our training program, great first-time contribution :smile: Would you please apply the `waiting-for-review` label when you finish so that we're notified of your PR.

**Comment by ManarOmar** [comment]
Hello @andrewnaguib and thank you, I checked the last box in the list, is there anything else I can do?

**Comment by ndrwnaguib** [comment]
You're welcome. I see you checked it. However, you forgot to do the actual labeling :smile: 

Steps:

* Click labels on the right panel
* Click `waiting for review`
:)

**Comment by ManarOmar** [comment]
the label on the right panel doesn't active for me to select the waiting for review label

**Comment by ndrwnaguib** [comment]
No problem. I’ll do it 😊

**Comment by ManarOmar** [comment]
Okay, thank you 😃

**Pull request merged**
